services:
  db:
    image: postgres:16
    container_name: jobs_db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: